export { default as setJestStatus } from './jest'
export { default as setLintStatus } from './eslint'
export { default as setFlowStatus } from './flow'
export { default as setSnykStatus } from './snyk'
export { default as setCodeClimateStatus } from './codeClimate'
